creation_rules:
  - path_regex: secrets/.*$
    age: >-
      age1jf4luvktqylgdyrf46w3hk78966mg8p4hag3w82zzwspgaplvvzqludadh,
      age16vyrjx6s6yhqcsj08lhxa3ykf0f7jlsyrlzxk0w640c47zgcn9csu8w2f8,
      age15je9u33w9g0m5vw5w4v02frrlr87dye9hcz54l3jl7uv486jseusu3jg55,
      age1f5djyw7p24t4qvfghz00lrh83f89d5lh62jl07j0jlh6j8pqse2qs4g47f
