{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
     # ./incus.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
      ./syspkg.nix
    ];

  users.users.qi = {
    uid = 501;
    extraGroups = [ "wheel" "orbstack" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/qi";
    homeMode = "700";
    useDefaultShell = true;
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Asia/Shanghai";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
MIICDDCCAbOgAwIBAgIRAJ4XwsGiJHaYkMU89tbQGSwwCgYIKoZIzj0EAwIwZjEd
MBsGA1UEChMUT3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5l
cnMgJiBTZXJ2aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9v
dCBDQTAeFw0yNTAxMTEwNzEwMzBaFw0zNTAxMTEwNzEwMzBaMGYxHTAbBgNVBAoT
FE9yYlN0YWNrIERldmVsb3BtZW50MR4wHAYDVQQLDBVDb250YWluZXJzICYgU2Vy
dmljZXMxJTAjBgNVBAMTHE9yYlN0YWNrIERldmVsb3BtZW50IFJvb3QgQ0EwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAAT6wf4sW4WJYYguOUzrnQ/8WjnZPAvdV7JZ
IC/FjopFxh9xzlFZk0bnG1WeMq+PaSotNSAmT3YRKAOvGBOqW8Rlo0IwQDAOBgNV
HQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUBhH5y00BREQu
XmmYyqMml6Xkm18wCgYIKoZIzj0EAwIDRwAwRAIgKEXweE1NyozXxNORoJ/LHc1p
AtDjG5cH81QPUvFNTsgCIG7j/bIuh4OOayu8YbjAaR1+tgvbU2pBRnK5J3ZjnNYo
-----END CERTIFICATE-----

    ''
  ];
  system.stateVersion = "26.05"; # Did you read the comment?
}
