# Ref from http://mutelight.org/practical-tmux

# Set XTerm key binding
setw -g xterm-keys on

# Set escape delay
# https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed
set-option -g escape-time 50

# Set colors
set-option -g default-terminal "screen-256color"

## Remap prefix from 'C-b' to 'Ctrl-`'
# unbind C-b
# set-option -g prefix C-`
# bind-key C-` send-prefix

# Use vim bindings
setw -g mode-keys vi

# Count sessions start at 1
set -g base-index 1

# Remap window navigation to vim
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R

# Switch panes, Fast window navigation
bind -n C-M-h select-pane -L
bind -n C-M-j select-pane -D
bind -n C-M-k select-pane -U
bind -n C-M-l select-pane -R
bind -n C-M-n next-window
bind -n C-M-p previous-window

# Reload source
# bind r source-file ~/.tmux.conf

# Set the title bar
set -g set-titles on
set -g set-titles-string '#(whoami)@#h :: [#S]'

# Set the default shell
# set-option -g default-shell /usr/bin/zsh

# Enable mouse support in ~/.tmux.conf
set -g mouse on
# set -g terminal-overrides 'xterm*:smcup@:rmcup@'

bind m setw -g mouse off \; display "Mouse OFF!"
bind M setw -g mouse on \; display "Mouse ON!"

# Set status bar
# set -g status-utf8 on
# set -g status-bg colour10
set -g status-fg black
set -g status-interval 5
set -g status-left-length 90
set -g status-right-length 60
# set -g status-left "#[fg=red]#(whoami)#[fg=white]::#[fg=blue]#(hostname -s)#[fg=white]::#[fg=black]#(curl ipecho.net/plain;echo) - "
set -g status-left "#[fg=black][#S] #{?pane_in_mode,#[fg=white#,dim],#[fg=brown#,dim]}#D #[fg=blue,dim]#{pane_tty} "
set -g status-justify left
set -g status-right '#[fg=black]#{user}@#H #[fg=blue,dim]%R %b-%d #[fg=black]%a'

setw -g automatic-rename on
set-window-option -g window-status-format '#[dem]#I:#[white]#W#[fg=white,dem]'
set-window-option -g window-status-current-format '#[fg=white,bold]#I#[fg=white]:#[fg=white]#W#[fg=dim]'

# reload SSH_AUTH_SOCK every time
set -g update-environment "SSH_AUTH_SOCK"

# true color
# set -g default-terminal "screen-256color"
# set -ga terminal-overrides ",xterm-256color*:Tc"

# bind-key / split-window -v ; resize-pane -D 10
bind-key / split-window -v -l 15


