## Icon theme + GTK plumbing, previously hand-maintained in ~/.icons and settings.ini.
{
  config,
  lib,
  pkgs,
  profileLevel,
  isLinux,
  inputs,
  ...
}:
let
  iconThemeName = "hicolor-plus";
  kdedConfig = config.xdg.configHome + "/kded6rc";
  kwriteconfig = lib.getExe' pkgs.kdePackages.kconfig "kwriteconfig6";
  ## Leftovers from kde-gtk-config; gtk.css below replaces the @import chain.
  kdeColorFiles = map (v: config.xdg.configHome + "/gtk-${v}/colors.css") [
    "3.0"
    "4.0"
  ];
in
lib.mkIf (profileLevel.guiBase && isLinux) {
  gtk = {
    enable = true;
    ## hicolor keeps the original look; Papirus fills missing names; breeze-dark last resort.
    iconTheme.name = iconThemeName;
    ## Provided system-wide by gnome-themes-extra (modules/niri).
    theme.name = "Adwaita";
    ## Pin gtk4 to the same theme; new hm defaults it to null below stateVersion 26.05.
    gtk4.theme.name = "Adwaita";
    gtk3.extraConfig = {
      gtk-font-name = "Noto Sans, 10";
      gtk-xft-antialias = 1;
      gtk-xft-dpi = 122880;
      gtk-xft-hinting = 1;
      gtk-xft-hintstyle = "hintslight";
      gtk-xft-rgba = "rgb";
    };
    ## Non-empty extraCss makes hm emit gtk.css, dropping the @import 'colors.css'.
    ## The breeze vars are inert under Adwaita, kept for a switch back to Breeze.
    gtk3.extraCss = builtins.readFile (inputs.my-dotfiles + "/.config/gtk-3.0/colors.css");
    gtk4.extraCss = builtins.readFile (inputs.my-dotfiles + "/.config/gtk-4.0/colors.css");
  };

  ## quickshell / portals resolve the icon theme through dconf, not settings.ini.
  dconf.settings."org/gnome/desktop/interface".icon-theme = iconThemeName;

  xdg.dataFile."icons/hicolor-plus/index.theme".text = ''
    [Icon Theme]
    Name=${iconThemeName}
    Comment=hicolor first, Papirus fills missing, breeze-dark last resort
    Inherits=hicolor,Papirus,breeze-dark
  '';

  ## kde-gtk-config is a plasma6 required package, so excludePackages cannot drop
  ## it. Its kded6 module rewrites the GTK css, segfaulting GTK/GIO clients on a
  ## stale file monitor closure. Reapplied each activation; kded6 rewrites kded6rc.
  home.activation = {
    disableKdedGtkConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      $DRY_RUN_CMD ${kwriteconfig} --file ${lib.escapeShellArg kdedConfig} --group Module-gtkconfig --key autoload false
    '';

    ## Derived files regenerated by kde-gtk-config, orphaned once gtk.css is ours.
    dropKdeGtkColors = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      $DRY_RUN_CMD ${lib.getExe' pkgs.coreutils "rm"} -f ${lib.escapeShellArgs kdeColorFiles}
    '';
  };
}
