# Generated by OrbStack.
# This WILL be overwritten in the future. Make a copy and update the include
# in configuration.nix if you want to keep your changes.

{ lib, config, modulesPath, pkgs, ... }:

let
  myvars = import ../lib/vars.nix;
in
{
  imports = [
    "${modulesPath}/virtualisation/lxc-container.nix"
  ];
  system.stateVersion = "26.05"; # Did you read the comment?
  time.timeZone = lib.mkForce "Asia/Shanghai";
  security.sudo.wheelNeedsPassword = false;

  # No bootloader（or shared kernel）
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.loader.efi.canTouchEfiVariables = lib.mkForce false;
  boot.loader.grub.enable = lib.mkForce false;
  boot.kernelPackages = lib.mkForce pkgs.linuxPackages;

  ## -------- Orbstack guest --------
  # Add OrbStack CLI tools to PATH
  environment.shellInit = ''
    . /opt/orbstack-guest/etc/profile-early
    # add your customizations here
    . /opt/orbstack-guest/etc/profile-late
  '';
  # Disable sshd
  services.openssh.enable = lib.mkForce false;
  programs.ssh.extraConfig = ''
    Include /opt/orbstack-guest/etc/ssh_config
  '';
  # Disable systemd-resolved
  services.resolved.enable = false;
  environment.etc."resolv.conf".source = "/opt/orbstack-guest/etc/resolv.conf";

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;
  users.users.${myvars.user} = {
    uid = 501;
    extraGroups = [ "wheel" "orbstack" ];

    # simulate isNormalUser, but with an arbitrary UID; so isNormalUser = false;
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "${myvars.homeDir}";
    homeMode = "700";
    useDefaultShell = true;
    openssh.authorizedKeys.keys = [];
    # shell = pkgs.zsh;
  };
  users.groups.orbstack.gid = 67278;

  nix.settings = {
    trusted-users = [ "${myvars.user}" ];
    substituters = [
      "http://nixos-dev.orb.local:8080/main" # nixos-dev's Attic cache
      "https://mirror.sjtu.edu.cn/nix-channels/store"
    ];
    trusted-public-keys = lib.mkAfter [
      "main:79VGDHuDHe5ct6x6FhBKpRoUL6ybL9D8XedX+7XfDis="
    ];

    extra-substituters = [
      # "http://nixos-dev.orb.local:8080/main"
      ## status: https://mirrors.ustc.edu.cn/status/
      # "https://mirrors.ustc.edu.cn/nix-channels/store"
      ## nix community's cache server
      "https://nix-community.cachix.org"
    ];
    ## will be appended to the system-level trusted-public-keys
    extra-trusted-public-keys = [
      ## nix community's cache server public key
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
    # indicate builder support for emulated architectures（Rosetta x86 simulate?）
    extra-platforms = [
      "x86_64-linux"
      "i686-linux"
    ];
  };

  nixpkgs.config = {
    allowUnfree = true; # allow non-FOSS pkgs
    allowUnsupportedSystem = true;
  };

  # Enable documentation
  documentation.man.enable = true;
  documentation.doc.enable = true;
  documentation.info.enable = true;

  ## -------- orb network --------
  networking = {
    dhcpcd = { 
      enable = false;
      ## Faster DHCP - OrbStack uses SLAAC exclusively
      # extraConfig = ''
      #   noarp
      #   noipv6
      # '';
    };
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Disable all GUI specialisation
  specialisation = lib.mkForce {};

  # systemd
  systemd.services."systemd-oomd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-userdbd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-udevd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-timesyncd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-timedated".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-portabled".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-nspawn@".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-machined".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-localed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-logind".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journald@".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journald".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journal-remote".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journal-upload".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-importd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-hostnamed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-homed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-networkd".serviceConfig.WatchdogSec = lib.mkIf config.systemd.network.enable 0;
}
