name: Update dependencies

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - run: nix flake update
      - run: |
          if git diff --quiet flake.lock; then
            echo "No changes to flake.lock"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add flake.lock
          git commit --no-verify -m "chore(deps): update flake.lock"
          git push
